In [1]:
import numpy as np

In [43]:
points = np.array([[0, 1], [2, 1], [3, 4]], dtype='float32')
points

array([[0., 1.],
       [2., 1.],
       [3., 4.]], dtype=float32)

In [44]:
x = points[:,0].reshape(-1, 1)
x

array([[0.],
       [2.],
       [3.]], dtype=float32)

In [48]:
y = points[:,1].reshape(-1, 1)
y

array([[1.],
       [1.],
       [4.]], dtype=float32)

## Calculate b

In [79]:
div = np.sum(x ** 2) - np.sum(x) ** 2 / len(points)
num = (np.sum(x * y) - (np.sum(x) * np.sum(y)) / len(points))
b = num / div

## Calculate a

In [81]:
a = (np.sum(y) - b * np.sum(x)) / len(points)

In [82]:
a, b

(0.5714285714285712, 0.8571428571428572)

In [84]:
6 /7, 4 /7

(0.8571428571428571, 0.5714285714285714)

In [85]:
from sklearn import datasets, linear_model

In [86]:
clf = linear_model.LinearRegression()

In [87]:
clf.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [93]:
clf.coef_, clf.intercept_

(array([[0.8571428]], dtype=float32), array([0.57142866], dtype=float32))

In [90]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_decision_function',
 '_estimator_type',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_preprocess_data',
 '_residues',
 '_set_intercept',
 'coef_',
 'copy_X',
 'fit',
 'fit_intercept',
 'get_params',
 'intercept_',
 'n_jobs',
 'normalize',
 'predict',
 'rank_',
 'score',
 'set_params',
 'singular_']